### ISSUE TITLE
Using this module crash the app

### ISSUE THREAD

**Issue by ghost** [trigger-corp/trigger.io-request#1]
I made a test on a app using the webview xhr method versus using this Request module.

After 10 query, the app crash and wee see a huge CPU usage in Chrome (using the debug tool)

After 100 query using the xhr in the webview, no problem at all...

What could explain the bad behaviour of this module ?

**Comment by antoinevg** [comment]
Can you provide a test case please?

**Comment by antoinevg** [comment]
Can you please provide a test case we can use to reproduce the crash?
